# Generated by Django 6.0.1 on 2026-02-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='average_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='predicted_cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectattendance',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subjectattendance',
            name='lectures_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectattendance',
            name='lectures_conducted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
