# Generated by Django 6.0.1 on 2026-02-13 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_semester_alter_student_risk_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='advisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
