# Generated by Django 6.0.1 on 2026-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_semester_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Sem 1'), (2, 'Sem 2'), (3, 'Sem 3'), (4, 'Sem 4'), (5, 'Sem 5'), (6, 'Sem 6'), (7, 'Sem 7'), (8, 'Sem 8')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology')], default='CS', max_length=10),
        ),
    ]
